### ISSUE TITLE
Строить модель по фактам

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#13]
И сохранять в JSON.

**Comment by pinbraerts** [comment]
Сейчас и точки, и отрезки?

**Comment by cblp** [comment]
Можешь начать только с точек

**Comment by cblp** [comment]
Ах да, надо сохранять модель в JSON.

**Comment by pinbraerts** [comment]
[Здесь](https://gist.github.com/pinbraerts/99ca8ee9a7b40c47b455b6d048da9802) прототип для точек, но, думаю, что будет совершенно другое строение.

**Comment by cblp** [comment]
Ок, отправляй пулреквест

**Comment by cblp** [comment]
или делай совершенно другое, если хочешь

**Comment by pinbraerts** [comment]
Сделал другое [там же](https://gist.github.com/pinbraerts/99ca8ee9a7b40c47b455b6d048da9802) с отрезками, чтобы нагляднее было, что код очень похожий. Посмотрите

**Comment by cblp** [comment]
буду читать только пулреквест. или словесное описание идеи. но мне кажется, что кодом описать у тебя получится лучше, чем словами.

**Comment by cblp** [comment]
done in #25
