### ISSUE TITLE
Исправить ошибки от Travis

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#22]
https://travis-ci.org/MCL1303/GeoPlot

**Comment by pinbraerts** [comment]
`chmod +x test\compare.py`

**Comment by cblp** [comment]
Это надо сделать

**Comment by pinbraerts** [comment]
`git add --chmod=+x test/compare.py` надо было делать, когда были изменения, если просто `chmod +x test/compare.py`, то в коммите не регистрируются изменения.

**Comment by cblp** [comment]
Если просто `chmod +x test/compare.py`, то в коммите отлично регистрируются изменения. Может, ты на винде коммитишь? Или на виндовой файловой системе?

**Comment by pinbraerts** [comment]
На винде

**Comment by cblp** [comment]
Первая команда `add --chmod` разве не работает?

**Comment by pinbraerts** [comment]
Нет, я делал, но это не засекается, как изменение

UPD: Сделал на телефоне, отправил пуллреквест, но тесты провалились из-за отсутствия томиты.

**Comment by pinbraerts** [comment]
В Travis'е нет томиты.

**Comment by pinbraerts** [comment]
И `language` у скрипта -- почему-то ruby, хотя на запуск это никак не влияет

**Comment by cblp** [comment]
> В Travis'е нет томиты.

Я почему-то не удивлён. Как предлагаешь решить эту проблему?

**Comment by cblp** [comment]
`language: ruby` ни на что не должно влиять
