### ISSUE TITLE
extract.py: вместо '*' использовать явный список файлов

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#31]

**Comment by pinbraerts** [comment]
Так это же для удобства или надо в `compare.py`&?

**Comment by cblp** [comment]
Если у меня есть список файлов, удобнее вызвать `extract.py` с этим списком или для каждого файла в отдельности, а не придумывать всякие волшебные звёздочки.

Special cases aren't special enough to break the rules.

**Comment by pinbraerts** [comment]
Можно вызвать со списком файлов

**Comment by cblp** [comment]
Значит, звёздочку можно убрать?

**Comment by pinbraerts** [comment]
Она для удобства, зачем убирать?

**Comment by cblp** [comment]
в чем заключается удобство? по-моему, неудобно лишний особый случай обрабатывать

**Comment by pinbraerts** [comment]
Удобство вызова

**Comment by cblp** [comment]
удобнее ведь вызывать с явным списком, ты снаружи знаешь уже список файлов

**Comment by pinbraerts** [comment]
Перечислять все файлы директории на разных платформах надо по-разному

**Comment by cblp** [comment]
На Линуксе и Макоси `ls test/data/input/*`. В винде как-то по-особенному?

**Comment by pinbraerts** [comment]
Ну я имел в виду `for`, а так можно с помощью `dir`, наверное

**Comment by pinbraerts** [comment]
Может сделать, чтобы `extract.py` обрабатывало только один файл а перебор файлов оставить на попечение пользователя? Тогда и #32 решится

**Comment by cblp** [comment]
отлично!

**Comment by cblp** [comment]
Я там упомянул `ls` только для примера. `for` и `dir` тоже не нужны. Юниксовые оболочки звёздочку в команде на список файлов. Пользователь пишет путь со звёздочкой, а программа вызывается с конкретным списком файлов. В винде разве не так?

**Comment by pinbraerts** [comment]
Вроде нет

**Comment by cblp** [comment]
done
