### ISSUE TITLE
Извлечь факты в XML руками

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#4]
Взять файл из тех, что выдаёт Томита, и для парочки задач написать факты.

Файлы нормализовать, то есть выкинуть лишние атрибуты и prettify.

**Comment by pinbraerts** [comment]
Можно всякие атрибуты от томиты типа _"sn"_, _"fw"_ не писать?

**Comment by cblp** [comment]
можно

**Comment by pinbraerts** [comment]
Готово

**Comment by cblp** [comment]
done
