### ISSUE TITLE
Написать программу для тестирования извлечения фактов

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#7]
сравнивая с эталонными

**Comment by pinbraerts** [comment]
Мы обсуждали, что `diff` или `git` подойдут.

**Comment by cblp** [comment]
Так вот, нужна программа/скрипт для запуска diff для нужных файлов.

**Comment by pinbraerts** [comment]
На Windows стандартная утилита для сравнения есть какая-нибудь?

**Comment by cblp** [comment]
разве что `fc`

**Comment by pinbraerts** [comment]
Сделано в #21
