### ISSUE TITLE
Обнаруживать Томита-парcер автоматически

### ISSUE THREAD

**Issue by cblp** [MCL1303/GeoPlot#9]
В зависимости от ОС искать файл с разным именем, на линуксе это `tomita-linux32` или `...64`, на маке `tomita-mac`.

**Comment by pinbraerts** [comment]
Сделано с помощью `where /Q %cmd%` на Windows и `which $cmd` на UNIX.

В [этом](https://github.com/MCL1303/GeoPlot/pull/16) пуллреквесте.
